apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Grafana"
  description: deployGrafana
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: guest
